//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWalker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Key {
            get {
                return ((string)(this["Key"]));
            }
            set {
                this["Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Steam\\SteamApps\\common\\Grand Theft Auto V")]
        public string GTAFolder {
            get {
                return ((string)(this["GTAFolder"]));
            }
            set {
                this["GTAFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompiledScriptFolder {
            get {
                return ((string)(this["CompiledScriptFolder"]));
            }
            set {
                this["CompiledScriptFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DecompiledScriptFolder {
            get {
                return ((string)(this["DecompiledScriptFolder"]));
            }
            set {
                this["DecompiledScriptFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GTAExeDumpFile {
            get {
                return ((string)(this["GTAExeDumpFile"]));
            }
            set {
                this["GTAExeDumpFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtractedTexturesFolder {
            get {
                return ((string)(this["ExtractedTexturesFolder"]));
            }
            set {
                this["ExtractedTexturesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtractedRawFilesFolder {
            get {
                return ((string)(this["ExtractedRawFilesFolder"]));
            }
            set {
                this["ExtractedRawFilesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtractedShadersFolder {
            get {
                return ((string)(this["ExtractedShadersFolder"]));
            }
            set {
                this["ExtractedShadersFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wireframe {
            get {
                return ((bool)(this["Wireframe"]));
            }
            set {
                this["Wireframe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Skydome {
            get {
                return ((bool)(this["Skydome"]));
            }
            set {
                this["Skydome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTimedEntities {
            get {
                return ((bool)(this["ShowTimedEntities"]));
            }
            set {
                this["ShowTimedEntities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCollisionMeshes {
            get {
                return ((bool)(this["ShowCollisionMeshes"]));
            }
            set {
                this["ShowCollisionMeshes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CollisionMeshRange {
            get {
                return ((int)(this["CollisionMeshRange"]));
            }
            set {
                this["CollisionMeshRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DynamicLOD {
            get {
                return ((bool)(this["DynamicLOD"]));
            }
            set {
                this["DynamicLOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DetailDist {
            get {
                return ((int)(this["DetailDist"]));
            }
            set {
                this["DetailDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Glokon Marker")]
        public string MarkerStyle {
            get {
                return ((string)(this["MarkerStyle"]));
            }
            set {
                this["MarkerStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Glokon Debug")]
        public string LocatorStyle {
            get {
                return ((string)(this["LocatorStyle"]));
            }
            set {
                this["LocatorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MarkerDepthClip {
            get {
                return ((bool)(this["MarkerDepthClip"]));
            }
            set {
                this["MarkerDepthClip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string BoundsStyle {
            get {
                return ((string)(this["BoundsStyle"]));
            }
            set {
                this["BoundsStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BoundsDepthClip {
            get {
                return ((bool)(this["BoundsDepthClip"]));
            }
            set {
                this["BoundsDepthClip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BoundsRange {
            get {
                return ((int)(this["BoundsRange"]));
            }
            set {
                this["BoundsRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowErrorConsole {
            get {
                return ((bool)(this["ShowErrorConsole"]));
            }
            set {
                this["ShowErrorConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Shadows {
            get {
                return ((bool)(this["Shadows"]));
            }
            set {
                this["Shadows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int ShadowCascades {
            get {
                return ((int)(this["ShadowCascades"]));
            }
            set {
                this["ShadowCascades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grass {
            get {
                return ((bool)(this["Grass"]));
            }
            set {
                this["Grass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStatusBar {
            get {
                return ((bool)(this["ShowStatusBar"]));
            }
            set {
                this["ShowStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WaitForChildren {
            get {
                return ((bool)(this["WaitForChildren"]));
            }
            set {
                this["WaitForChildren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2147483648")]
        public long CacheSize {
            get {
                return ((long)(this["CacheSize"]));
            }
            set {
                this["CacheSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double CacheTime {
            get {
                return ((double)(this["CacheTime"]));
            }
            set {
                this["CacheTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("536870912")]
        public long GPUGeometryCacheSize {
            get {
                return ((long)(this["GPUGeometryCacheSize"]));
            }
            set {
                this["GPUGeometryCacheSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1073741824")]
        public long GPUTextureCacheSize {
            get {
                return ((long)(this["GPUTextureCacheSize"]));
            }
            set {
                this["GPUTextureCacheSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("134217728")]
        public long GPUBoundCompCacheSize {
            get {
                return ((long)(this["GPUBoundCompCacheSize"]));
            }
            set {
                this["GPUBoundCompCacheSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double GPUCacheTime {
            get {
                return ((double)(this["GPUCacheTime"]));
            }
            set {
                this["GPUCacheTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double GPUCacheFlushTime {
            get {
                return ((double)(this["GPUCacheFlushTime"]));
            }
            set {
                this["GPUCacheFlushTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float CameraSmoothing {
            get {
                return ((float)(this["CameraSmoothing"]));
            }
            set {
                this["CameraSmoothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.005")]
        public float CameraSensitivity {
            get {
                return ((float)(this["CameraSensitivity"]));
            }
            set {
                this["CameraSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CameraFieldOfView {
            get {
                return ((float)(this["CameraFieldOfView"]));
            }
            set {
                this["CameraFieldOfView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string RenderMode {
            get {
                return ((string)(this["RenderMode"]));
            }
            set {
                this["RenderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DiffuseSampler")]
        public string RenderTextureSampler {
            get {
                return ((string)(this["RenderTextureSampler"]));
            }
            set {
                this["RenderTextureSampler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texture coord 1")]
        public string RenderTextureSamplerCoord {
            get {
                return ((string)(this["RenderTextureSamplerCoord"]));
            }
            set {
                this["RenderTextureSamplerCoord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Installers;_CommonRedist")]
        public string ExcludeFolders {
            get {
                return ((string)(this["ExcludeFolders"]));
            }
            set {
                this["ExcludeFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AnisotropicFiltering {
            get {
                return ((bool)(this["AnisotropicFiltering"]));
            }
            set {
                this["AnisotropicFiltering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HDR {
            get {
                return ((bool)(this["HDR"]));
            }
            set {
                this["HDR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowMaximized {
            get {
                return ((bool)(this["WindowMaximized"]));
            }
            set {
                this["WindowMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMods {
            get {
                return ((bool)(this["EnableMods"]));
            }
            set {
                this["EnableMods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DLC {
            get {
                return ((string)(this["DLC"]));
            }
            set {
                this["DLC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Move Forwards: W</string>
  <string>Move Backwards: S</string>
  <string>Move Left: A</string>
  <string>Move Right: D</string>
  <string>Move Up: R</string>
  <string>Move Down: F</string>
  <string>Move Slower / Zoom In: Z</string>
  <string>Move Faster / Zoom Out: X</string>
  <string>Toggle Mouse Select: C</string>
  <string>Toggle Toolbar: T</string>
  <string>Exit Edit Mode: Q</string>
  <string>Edit Position: W</string>
  <string>Edit Rotation: E</string>
  <string>Edit Scale: R</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KeyBindings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeyBindings"]));
            }
            set {
                this["KeyBindings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XInputLThumbInvert {
            get {
                return ((bool)(this["XInputLThumbInvert"]));
            }
            set {
                this["XInputLThumbInvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XInputRThumbInvert {
            get {
                return ((bool)(this["XInputRThumbInvert"]));
            }
            set {
                this["XInputRThumbInvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float XInputLThumbSensitivity {
            get {
                return ((float)(this["XInputLThumbSensitivity"]));
            }
            set {
                this["XInputLThumbSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float XInputRThumbSensitivity {
            get {
                return ((float)(this["XInputRThumbSensitivity"]));
            }
            set {
                this["XInputRThumbSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float XInputZoomSpeed {
            get {
                return ((float)(this["XInputZoomSpeed"]));
            }
            set {
                this["XInputZoomSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public float XInputMoveSpeed {
            get {
                return ((float)(this["XInputMoveSpeed"]));
            }
            set {
                this["XInputMoveSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MouseInvert {
            get {
                return ((bool)(this["MouseInvert"]));
            }
            set {
                this["MouseInvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberGTAFolder {
            get {
                return ((bool)(this["RememberGTAFolder"]));
            }
            set {
                this["RememberGTAFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string ProjectWindowTheme {
            get {
                return ((string)(this["ProjectWindowTheme"]));
            }
            set {
                this["ProjectWindowTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Windows")]
        public string ExplorerWindowTheme {
            get {
                return ((string)(this["ExplorerWindowTheme"]));
            }
            set {
                this["ExplorerWindowTheme"] = value;
            }
        }
    }
}
